url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Tinkerworks • Jelte Klas Wijnja" # the name of your site, e.g. ACME Corp.
email: "jelte1234@live.nl" # Shown in the footer and on the index.html 'about' page
permalink: none # We don't want dates to be included in post links, since we're building a portfolio
portrait_picture_path: "/images/portrait.png" # The portrait used on the main index.html 'about' page.

collections_dir: 'portfolio'

collections:
  design:
    output: true
    name: 'Design'
  cad:
    output: true
    name: 'CAD/CAM/3D printing'
    permalink: 'design/:name'
  tinkerworks_design:
    output: true
    name: 'Tinkerworks Design'
    permalink: 'design/:name'
  photography:
    output: true
    name: 'Photography'
  photo_various:
    output: true
    name: 'Various works'
    permalink: 'photography/:name'
  video:
    output: true
    name: 'Video'
    permalink: 'photography/:name'
  tinkerworks_photography:
    output: true
    name: 'Tinkerworks Photography'
    permalink: 'photography/:name'
  tinkering:
    output: true
    name: 'Tinkering'
  tinkerworks:
    output: true
    name: 'Tinkerworks'
    permalink: 'tinkering/:name'

